import {
  asked,
  didEvent,
  eventAtSec,
  type ClinicalFact,
  type EngineCase,
  type ManagementAction,
  type PhysicalExamAction,
  type RubricCriterion,
  type TestOrder,
} from "./engine";

const facts: ClinicalFact[] = [
  // história — o paciente conhece e verbaliza quando perguntado
  {
    id: "hda-inicio",
    category: "historia",
    label: "Início da dor",
    content: "A dor começou há cerca de 40 minutos, em repouso, assistindo televisão.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "hda-carater",
    category: "historia",
    label: "Caráter da dor",
    content: "Dor retroesternal em aperto, contínua, sem melhora com repouso.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "hda-irradiacao",
    category: "historia",
    label: "Irradiação",
    content: "Irradia para a mandíbula e para o braço esquerdo.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "hda-intensidade",
    category: "historia",
    label: "Intensidade",
    content: "Intensidade 8 em 10; a pior dor que já sentiu.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "hda-associados",
    category: "historia",
    label: "Sintomas associados",
    content: "Sudorese fria, náusea, falta de ar. Nega febre, tosse, vômito ou síncope.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "hda-fatores",
    category: "historia",
    label: "Fatores de melhora/piora",
    content: "Não muda com respiração nem com posição; nada aliviou até agora.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "ap-hipertensao",
    category: "antecedentes",
    label: "Hipertensão",
    content: "Hipertensa há 20 anos, acompanhamento irregular.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "ap-diabetes",
    category: "antecedentes",
    label: "Diabetes tipo 2",
    content: "Diabetes tipo 2 há 8 anos.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "ap-familiar",
    category: "antecedentes",
    label: "História familiar",
    content: "Pai faleceu de infarto aos 60 anos.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "med-uso",
    category: "medicamentos",
    label: "Medicamentos em uso",
    content: "Losartana 50 mg pela manhã e metformina 850 mg duas vezes ao dia.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "alergias",
    category: "alergias",
    label: "Alergias",
    content: "Nega alergias medicamentosas, inclusive a AAS.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "habito-tabagismo",
    category: "habitos",
    label: "Tabagismo",
    content: "Ex-tabagista, 30 maços-ano, parou há 5 anos.",
    patientKnows: true,
    initialState: "hidden",
  },
  {
    id: "sensivel-sildenafil",
    category: "medicamentos",
    label: "Uso recente de vasodilatador",
    content:
      "Nega uso de sildenafil ou similares. Confirma apenas se perguntada de forma direta e respeitosa.",
    patientKnows: true,
    initialState: "withheld_sensitive",
  },
  {
    id: "sensivel-medo",
    category: "historia",
    label: "Medo de morrer",
    content:
      "Tem muito medo de morrer como o pai; só verbaliza isso se acolhida com empatia.",
    patientKnows: true,
    initialState: "withheld_sensitive",
  },

  // exame físico — objetivos, o paciente NÃO conhece
  {
    id: "ef-estado-geral",
    category: "exame_fisico",
    label: "Estado geral",
    content: "Regular estado geral, ansiosa, pálida, sudoreica, mantém-se sentada.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "warn",
  },
  {
    id: "ef-pulso",
    category: "exame_fisico",
    label: "Pulso",
    content: "Pulso radial rítmico, 104 bpm, amplitude diminuída e simétrico.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "warn",
  },
  {
    id: "ef-pa",
    category: "exame_fisico",
    label: "Pressão arterial",
    content: "PA 158/96 mmHg em MSD; 154/94 mmHg em MSE.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "warn",
  },
  {
    id: "ef-ausculta-cardiaca",
    category: "exame_fisico",
    label: "Ausculta cardíaca",
    content: "Ritmo regular em 2 tempos, B4 audível, sem sopros ou atrito.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "warn",
  },
  {
    id: "ef-ausculta-pulmonar",
    category: "exame_fisico",
    label: "Ausculta pulmonar",
    content: "Estertores crepitantes em bases bilateralmente, murmúrio vesicular diminuído.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "crit",
  },
  {
    id: "ef-perfusao",
    category: "exame_fisico",
    label: "Perfusão periférica",
    content: "Extremidades frias, enchimento capilar 3 segundos, sudorese fria.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "crit",
  },
  {
    id: "ef-abdome",
    category: "exame_fisico",
    label: "Abdome",
    content: "Flácido, indolor, sem visceromegalias, ruídos hidroaéreos presentes.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "normal",
  },
  {
    id: "ef-mmii",
    category: "exame_fisico",
    label: "Membros inferiores",
    content: "Sem edema, sem sinais de trombose venosa profunda, panturrilhas livres.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "normal",
  },
  {
    id: "ef-neuro",
    category: "exame_fisico",
    label: "Neurológico",
    content: "Glasgow 15, lúcida e orientada, sem déficits focais.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "normal",
  },

  // exames complementares
  {
    id: "ex-ecg",
    category: "exame_complementar",
    label: "ECG 12 derivações",
    content: "Supradesnivelamento de ST de 3 mm em V2–V4 com imagem em espelho em parede inferior.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "crit",
  },
  {
    id: "ex-troponina",
    category: "exame_complementar",
    label: "Troponina T ultrassensível",
    content: "0,42 ng/mL (referência < 0,014).",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "crit",
  },
  {
    id: "ex-hemograma",
    category: "exame_complementar",
    label: "Hemograma",
    content: "Hb 13,8 g/dL · Leucócitos 9.400 · Plaquetas 232.000.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "normal",
  },
  {
    id: "ex-eletrolitos",
    category: "exame_complementar",
    label: "Eletrólitos e função renal",
    content: "Na 139 · K 4,1 · Creatinina 1,1 mg/dL · Ureia 42.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "normal",
  },
  {
    id: "ex-glicemia",
    category: "exame_complementar",
    label: "Glicemia capilar",
    content: "184 mg/dL.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "warn",
  },
  {
    id: "ex-rx",
    category: "exame_complementar",
    label: "Radiografia de tórax",
    content: "Congestão pulmonar leve, área cardíaca no limite superior, sem alargamento de mediastino.",
    patientKnows: false,
    initialState: "unknown_to_patient",
    status: "warn",
  },
  {
    id: "ex-dimero",
    category: "exame_complementar",
    label: "D-dímero",
    content: "Exame indisponível neste serviço no momento.",
    patientKnows: false,
    initialState: "unavailable",
    status: "normal",
  },
];

const physicalExams: PhysicalExamAction[] = [
  {
    id: "pe-estado-geral",
    label: "Estado geral e inspeção",
    group: "Geral",
    keywords: ["estado geral", "inspeção", "aparência"],
    reveals: ["ef-estado-geral"],
    durationSec: 20,
  },
  {
    id: "pe-pulso",
    label: "Pulso",
    group: "Cardiovascular",
    keywords: ["pulso", "frequência de pulso"],
    reveals: ["ef-pulso"],
    durationSec: 20,
  },
  {
    id: "pe-pa",
    label: "Pressão arterial (ambos os membros)",
    group: "Cardiovascular",
    keywords: ["pressão", "pa", "manguito"],
    reveals: ["ef-pa"],
    durationSec: 40,
  },
  {
    id: "pe-ausculta-cardiaca",
    label: "Ausculta cardíaca",
    group: "Cardiovascular",
    keywords: ["ausculta cardíaca", "coração", "bulhas"],
    reveals: ["ef-ausculta-cardiaca"],
    durationSec: 40,
  },
  {
    id: "pe-ausculta-pulmonar",
    label: "Ausculta pulmonar",
    group: "Respiratório",
    keywords: ["ausculta pulmonar", "pulmão", "tórax"],
    reveals: ["ef-ausculta-pulmonar"],
    durationSec: 40,
  },
  {
    id: "pe-perfusao",
    label: "Perfusão periférica",
    group: "Cardiovascular",
    keywords: ["perfusão", "enchimento capilar", "extremidades"],
    reveals: ["ef-perfusao"],
    durationSec: 20,
  },
  {
    id: "pe-abdome",
    label: "Abdome",
    group: "Abdominal",
    keywords: ["abdome", "barriga", "palpação abdominal"],
    reveals: ["ef-abdome"],
    durationSec: 40,
  },
  {
    id: "pe-mmii",
    label: "Membros inferiores",
    group: "Vascular",
    keywords: ["membros inferiores", "pernas", "panturrilha", "edema"],
    reveals: ["ef-mmii"],
    durationSec: 30,
  },
  {
    id: "pe-neuro",
    label: "Neurológico sumário",
    group: "Neurológico",
    keywords: ["neurológico", "glasgow", "consciência"],
    reveals: ["ef-neuro"],
    durationSec: 30,
  },
];

const tests: TestOrder[] = [
  { id: "t-ecg", label: "ECG 12 derivações", category: "eletro", reveals: ["ex-ecg"], turnaroundSec: 10 },
  { id: "t-glicemia", label: "Glicemia capilar", category: "beira-leito", reveals: ["ex-glicemia"], turnaroundSec: 5 },
  { id: "t-troponina", label: "Troponina T ultrassensível", category: "laboratorio", reveals: ["ex-troponina"], turnaroundSec: 45 },
  { id: "t-hemograma", label: "Hemograma", category: "laboratorio", reveals: ["ex-hemograma"], turnaroundSec: 40 },
  { id: "t-eletrolitos", label: "Eletrólitos e função renal", category: "laboratorio", reveals: ["ex-eletrolitos"], turnaroundSec: 45 },
  { id: "t-rx", label: "Radiografia de tórax", category: "imagem", reveals: ["ex-rx"], turnaroundSec: 60 },
  { id: "t-dimero", label: "D-dímero", category: "laboratorio", reveals: ["ex-dimero"], turnaroundSec: 30 },
];

const managements: ManagementAction[] = [
  { id: "m-monitor", label: "Monitorização contínua + oximetria", category: "monitorizacao", appropriate: true, note: "Monitorização precoce em dor torácica de alto risco." },
  { id: "m-acesso", label: "Acesso venoso periférico calibroso", category: "acesso", appropriate: true, note: "Permite terapia venosa imediata." },
  { id: "m-o2", label: "Oxigênio suplementar 3 L/min", category: "oxigenio", appropriate: true, note: "Indicado com SpO₂ 88%." },
  { id: "m-aas", label: "AAS 300 mg VO mastigado", category: "medicamento", appropriate: true, note: "Antiagregação imediata, reduz mortalidade." },
  { id: "m-clopidogrel", label: "Segundo antiagregante (clopidogrel/ticagrelor)", category: "medicamento", appropriate: true, note: "Dupla antiagregação antes da reperfusão." },
  { id: "m-nitrato", label: "Nitrato sublingual", category: "medicamento", appropriate: true, note: "Alívio da dor isquêmica; checar PA e uso de vasodilatador." },
  { id: "m-morfina", label: "Morfina IV se dor refratária", category: "medicamento", appropriate: true, note: "Analgesia de resgate." },
  { id: "m-hemodinamica", label: "Acionar hemodinâmica — angioplastia primária", category: "interconsulta", appropriate: true, note: "Reperfusão é a conduta que define o prognóstico." },
  { id: "m-transferencia", label: "Transferir para unidade coronariana", category: "transferencia", appropriate: true, note: "Cuidado contínuo após reperfusão." },
  { id: "m-fluidos", label: "Expansão volêmica agressiva 1000 mL", category: "fluidos", appropriate: false, note: "Risco de piora da congestão pulmonar nesta paciente." },
  { id: "m-alta", label: "Liberar para casa com analgésico", category: "procedimento", appropriate: false, note: "Conduta insegura em IAM com supra de ST." },
];

const rubric: RubricCriterion[] = [
  // rapport
  { id: "r-apresentacao", domain: "rapport", label: "Apresentou-se / cumprimentou a paciente", weight: 1, check: (c) => asked(c, "bom dia", "boa tarde", "boa noite", "meu nome", "sou o", "sou a", "olá") },
  { id: "r-empatia", domain: "rapport", label: "Acolheu o medo e o desconforto da paciente", weight: 1, check: (c) => asked(c, "calma", "entendo", "vamos cuidar", "medo", "tranquil", "sinto muito") },
  { id: "r-aberta", domain: "rapport", label: "Usou ao menos uma pergunta aberta", weight: 1, check: (c) => c.studentQuestions.some((q) => /como|o que|conte|me fale|descreva/i.test(q)) },

  // anamnese
  { id: "a-caracterizou", domain: "anamnese", label: "Caracterizou a dor (tipo, local, intensidade)", weight: 2, check: (c) => asked(c, "dor", "aperto", "intensidade", "doi", "dói") },
  { id: "a-tempo", domain: "anamnese", label: "Investigou início e duração", weight: 1, check: (c) => asked(c, "quando começou", "há quanto tempo", "quanto tempo", "início") },
  { id: "a-irradiacao", domain: "anamnese", label: "Investigou irradiação", weight: 1, check: (c) => asked(c, "irradia", "espalha", "braço", "mandíbula", "costas") },
  { id: "a-associados", domain: "anamnese", label: "Investigou sintomas associados", weight: 1, check: (c) => asked(c, "falta de ar", "suor", "náusea", "enjoo", "tontura", "palpitação", "vômito") },
  { id: "a-antecedentes", domain: "anamnese", label: "Investigou antecedentes e fatores de risco", weight: 1, check: (c) => asked(c, "pressão alta", "hipertens", "diabet", "fuma", "tabag", "colesterol", "família", "infarto") },
  { id: "a-medicamentos", domain: "anamnese", label: "Perguntou medicamentos em uso", weight: 1, check: (c) => asked(c, "medicament", "remédio", "toma algum", "usa algum") },
  { id: "a-alergias", domain: "anamnese", label: "Perguntou alergias", weight: 1, check: (c) => asked(c, "alergia", "alérgic") },

  // raciocínio
  { id: "rc-exame-cardio", domain: "raciocinio", label: "Examinou o aparelho cardiovascular", weight: 1, check: (c) => didEvent(c, "exame_fisico", "pe-ausculta-cardiaca") || didEvent(c, "exame_fisico", "pe-pulso") },
  { id: "rc-exame-pulmonar", domain: "raciocinio", label: "Auscultou os pulmões (identificou congestão)", weight: 1, check: (c) => didEvent(c, "exame_fisico", "pe-ausculta-pulmonar") },
  { id: "rc-perfusao", domain: "raciocinio", label: "Avaliou perfusão periférica", weight: 1, check: (c) => didEvent(c, "exame_fisico", "pe-perfusao") },
  { id: "rc-ecg", domain: "raciocinio", label: "Solicitou ECG", weight: 2, check: (c) => didEvent(c, "exame_solicitado", "t-ecg") },
  { id: "rc-troponina", domain: "raciocinio", label: "Solicitou marcador de necrose miocárdica", weight: 1, check: (c) => didEvent(c, "exame_solicitado", "t-troponina") },
  { id: "rc-sem-excesso", domain: "raciocinio", label: "Não solicitou exames irrelevantes para o quadro", weight: 1, check: (c) => !didEvent(c, "exame_solicitado", "t-dimero") },

  // diagnóstico
  { id: "d-hipotese", domain: "diagnostico", label: "Registrou hipótese diagnóstica", weight: 1, check: (c) => c.events.some((e) => e.kind === "hipotese") },
  { id: "d-correta", domain: "diagnostico", label: "Hipótese compatível com IAM com supra de ST", weight: 3, check: (c) => c.events.some((e) => e.kind === "hipotese" && /iam|infarto|supra|stemi|sca com supra/i.test(`${e.label} ${e.detail ?? ""}`)) },

  // conduta
  { id: "c-aas", domain: "conduta", label: "Administrou AAS", weight: 2, check: (c) => didEvent(c, "conduta", "m-aas") },
  { id: "c-o2", domain: "conduta", label: "Ofertou oxigênio (SpO₂ 88%)", weight: 1, check: (c) => didEvent(c, "conduta", "m-o2") },
  { id: "c-acesso", domain: "conduta", label: "Obteve acesso venoso", weight: 1, check: (c) => didEvent(c, "conduta", "m-acesso") },
  { id: "c-reperfusao", domain: "conduta", label: "Acionou reperfusão (hemodinâmica)", weight: 3, check: (c) => didEvent(c, "conduta", "m-hemodinamica") },
  { id: "c-nitrato", domain: "conduta", label: "Considerou nitrato/analgesia para a dor", weight: 1, check: (c) => didEvent(c, "conduta", "m-nitrato") || didEvent(c, "conduta", "m-morfina") },

  // segurança clínica / priorização
  { id: "s-monitor", domain: "seguranca", label: "Monitorizou a paciente precocemente", weight: 2, check: (c) => { const t = eventAtSec(c, "conduta", "m-monitor"); return t !== undefined && t <= 300; } },
  { id: "s-ecg-precoce", domain: "seguranca", label: "ECG solicitado nos primeiros 10 minutos", weight: 2, check: (c) => { const t = eventAtSec(c, "exame_solicitado", "t-ecg"); return t !== undefined && t <= 600; } },
  { id: "s-sem-alta", domain: "seguranca", label: "Não liberou a paciente para casa", weight: 2, check: (c) => !didEvent(c, "conduta", "m-alta") },
  { id: "s-sem-volume", domain: "seguranca", label: "Evitou expansão volêmica agressiva com congestão", weight: 1, check: (c) => !didEvent(c, "conduta", "m-fluidos") },
  { id: "s-reperfusao-tempo", domain: "seguranca", label: "Reperfusão acionada em tempo hábil", weight: 2, check: (c) => { const t = eventAtSec(c, "conduta", "m-hemodinamica"); return t !== undefined && t <= 900; } },
];

export const joanaCase: EngineCase = {
  id: "dor-toracica",
  patientTruth: {
    demographics: "Joana M., 68 anos, sexo feminino, 67 kg, aposentada, emergência (leito 4).",
    chiefComplaint: "dor torácica há 40 minutos",
    persona:
      "Joana, 68 anos, aposentada, ansiosa e falante, português coloquial do Brasil, frases curtas, assustada com a dor.",
    facts,
    diagnosis: "Infarto agudo do miocárdio com supradesnivelamento de ST (parede anterior)",
    differentials: [
      "Angina instável",
      "Dissecção aguda de aorta",
      "Tromboembolismo pulmonar",
      "Pericardite aguda",
    ],
    physiology:
      "Oclusão trombótica da artéria descendente anterior; disfunção sistólica incipiente gerando congestão pulmonar e hipoxemia (SpO₂ 88%).",
    complications: [
      "Fibrilação ventricular",
      "Edema agudo de pulmão",
      "Choque cardiogênico",
      "Bloqueio atrioventricular",
    ],
  },
  physicalExams,
  tests,
  managements,
  rubric,
};
